# Generated by Django 2.1.2 on 2018-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_basketmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketmodel',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='basketmodel',
            name='discription_product',
            field=models.TextField(blank=True, null=True),
        ),
    ]
