# Generated by Django 2.1.2 on 2018-11-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181119_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='products.CategoryProduct'),
        ),
        migrations.AlterField(
            model_name='basketmodel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='basketmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='products.Product'),
        ),
    ]
