# Generated by Django 2.1.2 on 2018-11-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181120_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketmodel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='basketmodel',
            name='product',
        ),
    ]
