# Generated by Django 2.1.2 on 2018-11-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_basketmodel_product_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='product_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
