# Generated by Django 2.1.2 on 2018-11-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20181122_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
