# Generated by Django 2.1.2 on 2018-11-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_basketmodel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='number',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
    ]
