# Generated by Django 2.1.2 on 2018-12-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20181202_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='product_basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='basket', to='products.Product'),
        ),
    ]
