# Generated by Django 2.1.3 on 2018-11-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_product',
            field=models.ImageField(upload_to='products/static/images/'),
        ),
    ]
