# Generated by Django 2.1.2 on 2018-11-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimages_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='test',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image_product',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
