# Generated by Django 2.1.2 on 2018-11-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_addcarmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addcarmodel',
            options={'verbose_name': 'Авто', 'verbose_name_plural': 'Автомобиль'},
        ),
        migrations.AlterField(
            model_name='addcarmodel',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
