# Generated by Django 2.1.2 on 2018-11-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181112_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addcarmodel',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.RemoveField(
            model_name='addcarmodel',
            name='image_product',
        ),
    ]
