# Generated by Django 2.1.2 on 2018-11-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20181114_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcarmodel',
            name='image_product',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
