# Generated by Django 2.1.2 on 2018-11-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_addcarmodel_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcarmodel',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to='image_new_car/'),
        ),
    ]
