# Generated by Django 2.1.2 on 2018-11-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20181115_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcarmodel',
            name='image_product',
            field=models.ImageField(blank=True, default='', upload_to='image_new_car/'),
            preserve_default=False,
        ),
    ]
