# Generated by Django 2.1.2 on 2018-11-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20181120_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
