# Generated by Django 2.1.2 on 2018-11-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number',
        ),
    ]
