# Generated by Django 2.1.2 on 2018-12-08 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0021_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likedone',
            field=models.ManyToManyField(default=True, null=True, related_name='users_video_main', to=settings.AUTH_USER_MODEL),
        ),
    ]
