# Generated by Django 2.1.2 on 2018-12-08 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_likedone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likedone',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_video_main', to=settings.AUTH_USER_MODEL),
        ),
    ]
