# Generated by Django 2.1.2 on 2019-02-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20181208_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image_product',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
